version: '3'
services:
  rest-api:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOSTNAME=redis
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=mysecretpassword
      - DATABASE_NAME=postgres  
    links:
      - postgres
    networks: 
      - backend     
    depends_on:
      - 'postgres'       
  postgres:
    image: "postgres:alpine"
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks: 
      - backend      
networks:
  backend:
